---
title: "Taller Coordenadas Geográficas"
author: "Maria Jose Duarte H"
format: 
  html: default
  pdf: default
---
# Apuntes del taller 

 - Datum Bogotá: es un sistema geodésico local porque el origen no coincide con el centro de masas terrestre. El datum se localizó en el Observatorio Astronómico de Bogotá. Para etsa clasificación se dividieron 6 sistemas de coordenadas locales para reducir el error a medida que se aleja del origen seleccionado y se ubicaron coordenadas evitando valores negativos. 

- MAGNA SIRGAS:  en este caso el origen si coincide con el centro de masa terrestre, por lo tanto se denomina Sistema coordenado geocentrico. 

- Sistema convencional de referencia terrestre, se complementa con la denominación del año de validez, debido a la dependencia que existe entre coordenadas y el tiempo, este sistema se extendió por MAGNA y el datum geodesico o el centro de masa está definido por el elipsoide GRS80. 

- El datum Bogotá muestra un error de aprox 250 m porque su origen se encuentra desplazado 530 m del geocentro. 

# Instrucciones del taller

### Archivos que conforman el shapefile 

Cundinamarca shp (líneas y formas) 

Cundinamarca sbx (junta las formas con la base de datos) 

Cundinamarca dbf (tabla de atributos)

Cundinamarca prj (sistema para bogota). 


### Principales sistemas de coordenadas geográficas 

Existen sistemas de coordenadas proyectadas o geográficas, las primeras son útiles para mediciones de área, latitud y longitud mientras las segundas se utilizan para la elaboración de mapas ya que ubican los puntos sobre la forma tridimensional de la tierra. 


| Sistema de coordenadas | Tipo | Descripción | EPSG |
|--------------------------|------|-------------|------|
| Bogotá 1975| Geográfico| Este sistema maneja el Datum geodésico antiguo que se basa en el elipsoide internacional de la proyección Gauss-kruger y cuyo origen es el Observatorio Atronómico Nacional de Bogotá| 4218 |
| MAGNA| Geográfico | Este se refiere a la red de estaciones instaladas por el IGAC, utiliza el elipsoide GRS80| 4686 |
| MAGNA SIRGAS 2018| Geográfico | Es la actualización adaptada para las Americas en el 2018| 7844 |
| MAGNA SIRGAS 2018 Origen Nacional|Proyectado | Es la proyección oficial en la que se toma un origen único, lo que no hace necesario dividir el país por zonas, se trabaja con un único origen | 9377 |
| MAGNA SIRGAS 2018 Colombia Bogotá Zone| Proyectado | Es la proyección anterior de la zona central de Colombia | 3116 |
| MAGNA SIRGAS Colombia West Zone| Proyectado | Es la proyección anterior de la zona occidental de Colombia | 4686 |
